// Generated by CoffeeScript 1.8.0
var nop;

if (typeof console === "undefined" || console === null) {
  nop = function() {};
  window.console = {
    log: nop,
    warn: nop,
    error: nop,
    debug: nop
  };
}

Bacon.Observable.prototype.skipNulls = (function() {
  var nonNull;
  nonNull = function(v) {
    return v != null;
  };
  return function() {
    return this.filter(nonNull);
  };
})();

Bacon.Observable.prototype.toProp = function(initialValue) {
  var $prop, value;
  $prop = this.toProperty.apply(this, arguments);
  value = void 0;
  $prop.get = function() {
    return value;
  };
  $prop.onValue(function(v) {
    return value = v;
  });
  return $prop;
};
